/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Html, useGLTF } from '@react-three/drei'

export function ComputerModel(props) {
  const { nodes, materials } = useGLTF('/assets/models/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Root" position={[0.732, 0, 0.151]} rotation={[Math.PI, 0, Math.PI]}>
        <group name="Computer" position={[0.708, 0, 1.438]}>
          <mesh
            name="Base"
            castShadow
            receiveShadow
            geometry={nodes.Base.geometry}
            material={materials.WhiteMaterial}
            position={[0, -0.125, 0]}
          />
          <group name="Monitor" position={[0, 1.25, -0.755]} rotation={[0.131, 0, 0]}>
            <mesh
              name="MonitorBase"
              castShadow
              receiveShadow
              geometry={nodes.MonitorBase.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0.125, 0.63]}
            />
            <mesh
              name="Screen"
              castShadow
              receiveShadow
              geometry={nodes.Screen.geometry}
              material={materials.WhiteMaterial}
              position={[0, 1.005, -0.495]}
            >
              <Html rotation-y={Math.PI} transform>
                <div className='text-[#1E4BF5] font-medium'>
                  WIP
                </div>
              </Html>
            </mesh>
          </group>
          <mesh
            name="MonitorBottom"
            castShadow
            receiveShadow
            geometry={nodes.MonitorBottom.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0.5, 0.031]}
          />
          <mesh
            name="Rotator"
            castShadow
            receiveShadow
            geometry={nodes.Rotator.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0.688, -0.125]}
          />
          <mesh
            name="RotatorBottom"
            castShadow
            receiveShadow
            geometry={nodes.RotatorBottom.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0.563, -0.125]}
          />
        </group>
        <group name="Keyboard" position={[0.725, 0, -0.874]} rotation={[0, -0.087, 0]}>
          <mesh
            name="KeyboardBody"
            castShadow
            receiveShadow
            geometry={nodes.KeyboardBody.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0, -0.875]}
          />
          <group name="Keys" position={[1.453, -0.094, -0.188]}>
            <mesh
              name="cuboid006"
              castShadow
              receiveShadow
              geometry={nodes.cuboid006.geometry}
              material={materials.WhiteMaterial}
              position={[-0.266, 0, 0.359]}
            />
            <mesh
              name="cuboid007"
              castShadow
              receiveShadow
              geometry={nodes.cuboid007.geometry}
              material={materials.WhiteMaterial}
              position={[-0.328, 0, 0.156]}
            />
            <mesh
              name="cuboid008"
              castShadow
              receiveShadow
              geometry={nodes.cuboid008.geometry}
              material={materials.WhiteMaterial}
              position={[-0.391, 0, -0.047]}
            />
            <mesh
              name="cuboid009"
              castShadow
              receiveShadow
              geometry={nodes.cuboid009.geometry}
              material={materials.WhiteMaterial}
              position={[-0.594, 0, -0.047]}
            />
            <mesh
              name="cuboid010"
              castShadow
              receiveShadow
              geometry={nodes.cuboid010.geometry}
              material={materials.WhiteMaterial}
              position={[-0.469, 0, 0.359]}
            />
            <mesh
              name="cuboid011"
              castShadow
              receiveShadow
              geometry={nodes.cuboid011.geometry}
              material={materials.WhiteMaterial}
              position={[-0.531, 0, 0.156]}
            />
            <mesh
              name="cuboid012"
              castShadow
              receiveShadow
              geometry={nodes.cuboid012.geometry}
              material={materials.WhiteMaterial}
              position={[-0.797, 0, -0.047]}
            />
            <mesh
              name="cuboid013"
              castShadow
              receiveShadow
              geometry={nodes.cuboid013.geometry}
              material={materials.WhiteMaterial}
              position={[-0.672, 0, 0.359]}
            />
            <mesh
              name="cuboid014"
              castShadow
              receiveShadow
              geometry={nodes.cuboid014.geometry}
              material={materials.WhiteMaterial}
              position={[-0.734, 0, 0.156]}
            />
            <mesh
              name="cuboid015"
              castShadow
              receiveShadow
              geometry={nodes.cuboid015.geometry}
              material={materials.WhiteMaterial}
              position={[-1, 0, -0.047]}
            />
            <mesh
              name="cuboid016"
              castShadow
              receiveShadow
              geometry={nodes.cuboid016.geometry}
              material={materials.WhiteMaterial}
              position={[-0.875, 0, 0.359]}
            />
            <mesh
              name="cuboid017"
              castShadow
              receiveShadow
              geometry={nodes.cuboid017.geometry}
              material={materials.WhiteMaterial}
              position={[-0.938, 0, 0.156]}
            />
            <mesh
              name="cuboid018"
              castShadow
              receiveShadow
              geometry={nodes.cuboid018.geometry}
              material={materials.WhiteMaterial}
              position={[-1.203, 0, -0.047]}
            />
            <mesh
              name="cuboid019"
              castShadow
              receiveShadow
              geometry={nodes.cuboid019.geometry}
              material={materials.WhiteMaterial}
              position={[-1.078, 0, 0.359]}
            />
            <mesh
              name="cuboid020"
              castShadow
              receiveShadow
              geometry={nodes.cuboid020.geometry}
              material={materials.WhiteMaterial}
              position={[-1.141, 0, 0.156]}
            />
            <mesh
              name="cuboid021"
              castShadow
              receiveShadow
              geometry={nodes.cuboid021.geometry}
              material={materials.WhiteMaterial}
              position={[-1.406, 0, -0.047]}
            />
            <mesh
              name="cuboid022"
              castShadow
              receiveShadow
              geometry={nodes.cuboid022.geometry}
              material={materials.WhiteMaterial}
              position={[-1.281, 0, 0.359]}
            />
            <mesh
              name="cuboid023"
              castShadow
              receiveShadow
              geometry={nodes.cuboid023.geometry}
              material={materials.WhiteMaterial}
              position={[-1.344, 0, 0.156]}
            />
            <mesh
              name="cuboid024"
              castShadow
              receiveShadow
              geometry={nodes.cuboid024.geometry}
              material={materials.WhiteMaterial}
              position={[-1.609, 0, -0.047]}
            />
            <mesh
              name="cuboid025"
              castShadow
              receiveShadow
              geometry={nodes.cuboid025.geometry}
              material={materials.WhiteMaterial}
              position={[-1.484, 0, 0.359]}
            />
            <mesh
              name="cuboid026"
              castShadow
              receiveShadow
              geometry={nodes.cuboid026.geometry}
              material={materials.WhiteMaterial}
              position={[-1.547, 0, 0.156]}
            />
            <mesh
              name="cuboid027"
              castShadow
              receiveShadow
              geometry={nodes.cuboid027.geometry}
              material={materials.WhiteMaterial}
              position={[-1.813, 0, -0.047]}
            />
            <mesh
              name="cuboid028"
              castShadow
              receiveShadow
              geometry={nodes.cuboid028.geometry}
              material={materials.WhiteMaterial}
              position={[-1.688, 0, 0.359]}
            />
            <mesh
              name="cuboid029"
              castShadow
              receiveShadow
              geometry={nodes.cuboid029.geometry}
              material={materials.WhiteMaterial}
              position={[-1.75, 0, 0.156]}
            />
            <mesh
              name="cuboid030"
              castShadow
              receiveShadow
              geometry={nodes.cuboid030.geometry}
              material={materials.WhiteMaterial}
              position={[-2.016, 0, -0.047]}
            />
            <mesh
              name="cuboid031"
              castShadow
              receiveShadow
              geometry={nodes.cuboid031.geometry}
              material={materials.WhiteMaterial}
              position={[-2.219, 0, -0.047]}
            />
            <mesh
              name="cuboid032"
              castShadow
              receiveShadow
              geometry={nodes.cuboid032.geometry}
              material={materials.WhiteMaterial}
              position={[-1.891, 0, 0.359]}
            />
            <mesh
              name="cuboid033"
              castShadow
              receiveShadow
              geometry={nodes.cuboid033.geometry}
              material={materials.WhiteMaterial}
              position={[-2.094, 0, 0.359]}
            />
            <mesh
              name="cuboid034"
              castShadow
              receiveShadow
              geometry={nodes.cuboid034.geometry}
              material={materials.WhiteMaterial}
              position={[-2.297, 0, 0.359]}
            />
            <mesh
              name="cuboid035"
              castShadow
              receiveShadow
              geometry={nodes.cuboid035.geometry}
              material={materials.WhiteMaterial}
              position={[-2.5, 0, 0.359]}
            />
            <mesh
              name="cuboid036"
              castShadow
              receiveShadow
              geometry={nodes.cuboid036.geometry}
              material={materials.WhiteMaterial}
              position={[-1.953, 0, 0.156]}
            />
            <mesh
              name="cuboid037"
              castShadow
              receiveShadow
              geometry={nodes.cuboid037.geometry}
              material={materials.WhiteMaterial}
              position={[-2.156, 0, 0.156]}
            />
            <mesh
              name="cuboid038"
              castShadow
              receiveShadow
              geometry={nodes.cuboid038.geometry}
              material={materials.WhiteMaterial}
              position={[-2.359, 0, 0.156]}
            />
            <mesh
              name="cuboid039"
              castShadow
              receiveShadow
              geometry={nodes.cuboid039.geometry}
              material={materials.WhiteMaterial}
              position={[-0.609, 0, 0.563]}
            />
            <mesh
              name="cuboid040"
              castShadow
              receiveShadow
              geometry={nodes.cuboid040.geometry}
              material={materials.WhiteMaterial}
              position={[-0.813, 0, 0.563]}
            />
            <mesh
              name="cuboid041"
              castShadow
              receiveShadow
              geometry={nodes.cuboid041.geometry}
              material={materials.WhiteMaterial}
              position={[-1.016, 0, 0.563]}
            />
            <mesh
              name="cuboid042"
              castShadow
              receiveShadow
              geometry={nodes.cuboid042.geometry}
              material={materials.WhiteMaterial}
              position={[-1.219, 0, 0.563]}
            />
            <mesh
              name="cuboid043"
              castShadow
              receiveShadow
              geometry={nodes.cuboid043.geometry}
              material={materials.WhiteMaterial}
              position={[-1.422, 0, 0.563]}
            />
            <mesh
              name="cuboid044"
              castShadow
              receiveShadow
              geometry={nodes.cuboid044.geometry}
              material={materials.WhiteMaterial}
              position={[-1.625, 0, 0.563]}
            />
            <mesh
              name="cuboid045"
              castShadow
              receiveShadow
              geometry={nodes.cuboid045.geometry}
              material={materials.WhiteMaterial}
              position={[-1.828, 0, 0.563]}
            />
            <mesh
              name="cuboid046"
              castShadow
              receiveShadow
              geometry={nodes.cuboid046.geometry}
              material={materials.WhiteMaterial}
              position={[-2.031, 0, 0.563]}
            />
            <mesh
              name="cuboid047"
              castShadow
              receiveShadow
              geometry={nodes.cuboid047.geometry}
              material={materials.WhiteMaterial}
              position={[-2.234, 0, 0.563]}
            />
            <mesh
              name="cuboid048"
              castShadow
              receiveShadow
              geometry={nodes.cuboid048.geometry}
              material={materials.WhiteMaterial}
              position={[-2.438, 0, 0.563]}
            />
            <mesh
              name="cuboid049"
              castShadow
              receiveShadow
              geometry={nodes.cuboid049.geometry}
              material={materials.WhiteMaterial}
              position={[-2.641, 0, 0.563]}
            />
            <mesh
              name="cuboid050"
              castShadow
              receiveShadow
              geometry={nodes.cuboid050.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, -0.047]}
            />
            <mesh
              name="cuboid051"
              castShadow
              receiveShadow
              geometry={nodes.cuboid051.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.359]}
            />
            <mesh
              name="cuboid052"
              castShadow
              receiveShadow
              geometry={nodes.cuboid052.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, 0.359]}
            />
            <mesh
              name="cuboid053"
              castShadow
              receiveShadow
              geometry={nodes.cuboid053.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, -0.047]}
            />
            <mesh
              name="cuboid054"
              castShadow
              receiveShadow
              geometry={nodes.cuboid054.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.156]}
            />
            <mesh
              name="cuboid055"
              castShadow
              receiveShadow
              geometry={nodes.cuboid055.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, -0.25]}
            />
            <mesh
              name="cuboid056"
              castShadow
              receiveShadow
              geometry={nodes.cuboid056.geometry}
              material={materials.WhiteMaterial}
              position={[-0.266, 0, -0.25]}
            />
            <mesh
              name="cuboid057"
              castShadow
              receiveShadow
              geometry={nodes.cuboid057.geometry}
              material={materials.WhiteMaterial}
              position={[-0.531, 0, -0.25]}
            />
            <mesh
              name="cuboid058"
              castShadow
              receiveShadow
              geometry={nodes.cuboid058.geometry}
              material={materials.WhiteMaterial}
              position={[-2.234, 0, -0.25]}
            />
            <mesh
              name="cuboid059"
              castShadow
              receiveShadow
              geometry={nodes.cuboid059.geometry}
              material={materials.WhiteMaterial}
              position={[-1.969, 0, -0.25]}
            />
            <mesh
              name="cuboid060"
              castShadow
              receiveShadow
              geometry={nodes.cuboid060.geometry}
              material={materials.WhiteMaterial}
              position={[-1.703, 0, -0.25]}
            />
            <mesh
              name="cuboid061"
              castShadow
              receiveShadow
              geometry={nodes.cuboid061.geometry}
              material={materials.WhiteMaterial}
              position={[-2.5, 0, -0.25]}
            />
            <mesh
              name="cuboid062"
              castShadow
              receiveShadow
              geometry={nodes.cuboid062.geometry}
              material={materials.WhiteMaterial}
              position={[-2.766, 0, -0.25]}
            />
            <mesh
              name="Key_1"
              castShadow
              receiveShadow
              geometry={nodes.Key_1.geometry}
              material={materials.WhiteMaterial}
              position={[-0.203, 0, 0.563]}
            />
            <mesh
              name="Key_2"
              castShadow
              receiveShadow
              geometry={nodes.Key_2.geometry}
              material={materials.WhiteMaterial}
              position={[-0.406, 0, 0.563]}
            />
            <mesh
              name="Key_Enter"
              castShadow
              receiveShadow
              geometry={nodes.Key_Enter.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, 0.156]}
            />
            <mesh
              name="Key_Esc"
              castShadow
              receiveShadow
              geometry={nodes.Key_Esc.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.563]}
            />
          </group>
        </group>
        <group name="Mouse" position={[-1.297, 0, -0.461]} rotation={[0, Math.PI / 8, 0]}>
          <mesh
            name="MouseBody"
            castShadow
            receiveShadow
            geometry={nodes.MouseBody.geometry}
            material={materials.WhiteMaterial}
            position={[0, -0.125, -0.063]}
          />
          <mesh
            name="MouseWheel"
            castShadow
            receiveShadow
            geometry={nodes.MouseWheel.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0.23, 0.118]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1.234]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/computer.gltf')
