/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Html, useGLTF } from '@react-three/drei'

export function ComputerModel(props) {
  const { nodes, materials } = useGLTF('/assets/models/computer.glb')
  return (
    <group {...props} dispose={null}>
      <group name="ComputerRoot" position={[0.732, 0, 0.151]} rotation={[Math.PI, 0, Math.PI]}>
        <group name="Computer" position={[0.708, 0, 1.438]}>
          <mesh
            name="Base"
            castShadow
            receiveShadow
            geometry={nodes.Base.geometry}
            material={materials.WhiteMaterial}
            position={[0, -0.125, 0]}
          />
          <group name="Monitor" position={[0, 1.25, -0.755]} rotation={[0.131, 0, 0]}>
            <mesh
              name="MonitorBase"
              castShadow
              receiveShadow
              geometry={nodes.MonitorBase.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0.125, 0.63]}
            />
            <mesh
              name="Screen"
              castShadow
              receiveShadow
              geometry={nodes.Screen.geometry}
              material={materials.WhiteMaterial}
              position={[0, 1.005, -0.495]}
            >
              <Html rotation-y={Math.PI} transform>
                <div className='text-[#1E4BF5] font-[Monument] items-center text-center'>
                  WIP
                </div>
              </Html>
            </mesh>
          </group>
        </group>
        <group name="Keyboard" position={[0.725, 0, -0.874]} rotation={[0, -0.087, 0]}>
          <mesh
            name="KeyboardBody"
            castShadow
            receiveShadow
            geometry={nodes.KeyboardBody.geometry}
            material={materials.WhiteMaterial}
            position={[0, 0, -0.875]}
          />
          <group name="Keys" position={[1.453, -0.094, -0.188]}>
            <mesh
              name="Key_0"
              castShadow
              receiveShadow
              geometry={nodes.Key_0.geometry}
              material={materials.WhiteMaterial}
              position={[-2.031, 0, 0.563]}
            />
            <mesh
              name="Key_1"
              castShadow
              receiveShadow
              geometry={nodes.Key_1.geometry}
              material={materials.WhiteMaterial}
              position={[-0.203, 0, 0.563]}
            />
            <mesh
              name="Key_2"
              castShadow
              receiveShadow
              geometry={nodes.Key_2.geometry}
              material={materials.WhiteMaterial}
              position={[-0.406, 0, 0.563]}
            />
            <mesh
              name="Key_3"
              castShadow
              receiveShadow
              geometry={nodes.Key_3.geometry}
              material={materials.WhiteMaterial}
              position={[-0.609, 0, 0.563]}
            />
            <mesh
              name="Key_4"
              castShadow
              receiveShadow
              geometry={nodes.Key_4.geometry}
              material={materials.WhiteMaterial}
              position={[-0.813, 0, 0.563]}
            />
            <mesh
              name="Key_5"
              castShadow
              receiveShadow
              geometry={nodes.Key_5.geometry}
              material={materials.WhiteMaterial}
              position={[-1.016, 0, 0.563]}
            />
            <mesh
              name="Key_6"
              castShadow
              receiveShadow
              geometry={nodes.Key_6.geometry}
              material={materials.WhiteMaterial}
              position={[-1.219, 0, 0.563]}
            />
            <mesh
              name="Key_7"
              castShadow
              receiveShadow
              geometry={nodes.Key_7.geometry}
              material={materials.WhiteMaterial}
              position={[-1.422, 0, 0.563]}
            />
            <mesh
              name="Key_8"
              castShadow
              receiveShadow
              geometry={nodes.Key_8.geometry}
              material={materials.WhiteMaterial}
              position={[-1.625, 0, 0.563]}
            />
            <mesh
              name="Key_9"
              castShadow
              receiveShadow
              geometry={nodes.Key_9.geometry}
              material={materials.WhiteMaterial}
              position={[-1.828, 0, 0.563]}
            />
            <mesh
              name="Key_A"
              castShadow
              receiveShadow
              geometry={nodes.Key_A.geometry}
              material={materials.WhiteMaterial}
              position={[-0.328, 0, 0.156]}
            />
            <mesh
              name="Key_AltLeft"
              castShadow
              receiveShadow
              geometry={nodes.Key_AltLeft.geometry}
              material={materials.WhiteMaterial}
              position={[-0.531, 0, -0.25]}
            />
            <mesh
              name="Key_AltRight"
              castShadow
              receiveShadow
              geometry={nodes.Key_AltRight.geometry}
              material={materials.WhiteMaterial}
              position={[-1.969, 0, -0.25]}
            />
            <mesh
              name="Key_B"
              castShadow
              receiveShadow
              geometry={nodes.Key_B.geometry}
              material={materials.WhiteMaterial}
              position={[-1.203, 0, -0.047]}
            />
            <mesh
              name="Key_Backslash"
              castShadow
              receiveShadow
              geometry={nodes.Key_Backslash.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, 0.359]}
            />
            <mesh
              name="Key_Backspace"
              castShadow
              receiveShadow
              geometry={nodes.Key_Backspace.geometry}
              material={materials.WhiteMaterial}
              position={[-2.641, 0, 0.563]}
            />
            <mesh
              name="Key_BrackLeft"
              castShadow
              receiveShadow
              geometry={nodes.Key_BrackLeft.geometry}
              material={materials.WhiteMaterial}
              position={[-2.297, 0, 0.359]}
            />
            <mesh
              name="Key_BrackRight"
              castShadow
              receiveShadow
              geometry={nodes.Key_BrackRight.geometry}
              material={materials.WhiteMaterial}
              position={[-2.5, 0, 0.359]}
            />
            <mesh
              name="Key_C"
              castShadow
              receiveShadow
              geometry={nodes.Key_C.geometry}
              material={materials.WhiteMaterial}
              position={[-0.797, 0, -0.047]}
            />
            <mesh
              name="Key_CapsLock"
              castShadow
              receiveShadow
              geometry={nodes.Key_CapsLock.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.156]}
            />
            <mesh
              name="Key_Comma"
              castShadow
              receiveShadow
              geometry={nodes.Key_Comma.geometry}
              material={materials.WhiteMaterial}
              position={[-1.813, 0, -0.047]}
            />
            <mesh
              name="Key_CtrlLeft"
              castShadow
              receiveShadow
              geometry={nodes.Key_CtrlLeft.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, -0.25]}
            />
            <mesh
              name="Key_CtrlRight"
              castShadow
              receiveShadow
              geometry={nodes.Key_CtrlRight.geometry}
              material={materials.WhiteMaterial}
              position={[-2.766, 0, -0.25]}
            />
            <mesh
              name="Key_CtxMenu"
              castShadow
              receiveShadow
              geometry={nodes.Key_CtxMenu.geometry}
              material={materials.WhiteMaterial}
              position={[-2.5, 0, -0.25]}
            />
            <mesh
              name="Key_D"
              castShadow
              receiveShadow
              geometry={nodes.Key_D.geometry}
              material={materials.WhiteMaterial}
              position={[-0.734, 0, 0.156]}
            />
            <mesh
              name="Key_Dot"
              castShadow
              receiveShadow
              geometry={nodes.Key_Dot.geometry}
              material={materials.WhiteMaterial}
              position={[-2.016, 0, -0.047]}
            />
            <mesh
              name="Key_E"
              castShadow
              receiveShadow
              geometry={nodes.Key_E.geometry}
              material={materials.WhiteMaterial}
              position={[-0.672, 0, 0.359]}
            />
            <mesh
              name="Key_Enter"
              castShadow
              receiveShadow
              geometry={nodes.Key_Enter.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, 0.156]}
            />
            <mesh
              name="Key_Esc"
              castShadow
              receiveShadow
              geometry={nodes.Key_Esc.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.563]}
            />
            <mesh
              name="Key_F"
              castShadow
              receiveShadow
              geometry={nodes.Key_F.geometry}
              material={materials.WhiteMaterial}
              position={[-0.938, 0, 0.156]}
            />
            <mesh
              name="Key_G"
              castShadow
              receiveShadow
              geometry={nodes.Key_G.geometry}
              material={materials.WhiteMaterial}
              position={[-1.141, 0, 0.156]}
            />
            <mesh
              name="Key_H"
              castShadow
              receiveShadow
              geometry={nodes.Key_H.geometry}
              material={materials.WhiteMaterial}
              position={[-1.344, 0, 0.156]}
            />
            <mesh
              name="Key_I"
              castShadow
              receiveShadow
              geometry={nodes.Key_I.geometry}
              material={materials.WhiteMaterial}
              position={[-1.688, 0, 0.359]}
            />
            <mesh
              name="Key_J"
              castShadow
              receiveShadow
              geometry={nodes.Key_J.geometry}
              material={materials.WhiteMaterial}
              position={[-1.547, 0, 0.156]}
            />
            <mesh
              name="Key_K"
              castShadow
              receiveShadow
              geometry={nodes.Key_K.geometry}
              material={materials.WhiteMaterial}
              position={[-1.75, 0, 0.156]}
            />
            <mesh
              name="Key_L"
              castShadow
              receiveShadow
              geometry={nodes.Key_L.geometry}
              material={materials.WhiteMaterial}
              position={[-1.953, 0, 0.156]}
            />
            <mesh
              name="Key_M"
              castShadow
              receiveShadow
              geometry={nodes.Key_M.geometry}
              material={materials.WhiteMaterial}
              position={[-1.609, 0, -0.047]}
            />
            <mesh
              name="Key_MetaLeft"
              castShadow
              receiveShadow
              geometry={nodes.Key_MetaLeft.geometry}
              material={materials.WhiteMaterial}
              position={[-0.266, 0, -0.25]}
            />
            <mesh
              name="Key_MetaRight"
              castShadow
              receiveShadow
              geometry={nodes.Key_MetaRight.geometry}
              material={materials.WhiteMaterial}
              position={[-2.234, 0, -0.25]}
            />
            <mesh
              name="Key_Minus"
              castShadow
              receiveShadow
              geometry={nodes.Key_Minus.geometry}
              material={materials.WhiteMaterial}
              position={[-2.234, 0, 0.563]}
            />
            <mesh
              name="Key_N"
              castShadow
              receiveShadow
              geometry={nodes.Key_N.geometry}
              material={materials.WhiteMaterial}
              position={[-1.406, 0, -0.047]}
            />
            <mesh
              name="Key_O"
              castShadow
              receiveShadow
              geometry={nodes.Key_O.geometry}
              material={materials.WhiteMaterial}
              position={[-1.891, 0, 0.359]}
            />
            <mesh
              name="Key_P"
              castShadow
              receiveShadow
              geometry={nodes.Key_P.geometry}
              material={materials.WhiteMaterial}
              position={[-2.094, 0, 0.359]}
            />
            <mesh
              name="Key_Plus"
              castShadow
              receiveShadow
              geometry={nodes.Key_Plus.geometry}
              material={materials.WhiteMaterial}
              position={[-2.438, 0, 0.563]}
            />
            <mesh
              name="Key_Q"
              castShadow
              receiveShadow
              geometry={nodes.Key_Q.geometry}
              material={materials.WhiteMaterial}
              position={[-0.266, 0, 0.359]}
            />
            <mesh
              name="Key_QMark"
              castShadow
              receiveShadow
              geometry={nodes.Key_QMark.geometry}
              material={materials.WhiteMaterial}
              position={[-2.219, 0, -0.047]}
            />
            <mesh
              name="Key_Quote"
              castShadow
              receiveShadow
              geometry={nodes.Key_Quote.geometry}
              material={materials.WhiteMaterial}
              position={[-2.359, 0, 0.156]}
            />
            <mesh
              name="Key_R"
              castShadow
              receiveShadow
              geometry={nodes.Key_R.geometry}
              material={materials.WhiteMaterial}
              position={[-0.875, 0, 0.359]}
            />
            <mesh
              name="Key_S"
              castShadow
              receiveShadow
              geometry={nodes.Key_S.geometry}
              material={materials.WhiteMaterial}
              position={[-0.531, 0, 0.156]}
            />
            <mesh
              name="Key_SemiCol"
              castShadow
              receiveShadow
              geometry={nodes.Key_SemiCol.geometry}
              material={materials.WhiteMaterial}
              position={[-2.156, 0, 0.156]}
            />
            <mesh
              name="Key_ShiftLeft"
              castShadow
              receiveShadow
              geometry={nodes.Key_ShiftLeft.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, -0.047]}
            />
            <mesh
              name="Key_ShiftRight"
              castShadow
              receiveShadow
              geometry={nodes.Key_ShiftRight.geometry}
              material={materials.WhiteMaterial}
              position={[-2.703, 0, -0.047]}
            />
            <mesh
              name="Key_Space"
              castShadow
              receiveShadow
              geometry={nodes.Key_Space.geometry}
              material={materials.WhiteMaterial}
              position={[-1.703, 0, -0.25]}
            />
            <mesh
              name="Key_T"
              castShadow
              receiveShadow
              geometry={nodes.Key_T.geometry}
              material={materials.WhiteMaterial}
              position={[-1.078, 0, 0.359]}
            />
            <mesh
              name="Key_Tab"
              castShadow
              receiveShadow
              geometry={nodes.Key_Tab.geometry}
              material={materials.WhiteMaterial}
              position={[0, 0, 0.359]}
            />
            <mesh
              name="Key_U"
              castShadow
              receiveShadow
              geometry={nodes.Key_U.geometry}
              material={materials.WhiteMaterial}
              position={[-1.484, 0, 0.359]}
            />
            <mesh
              name="Key_V"
              castShadow
              receiveShadow
              geometry={nodes.Key_V.geometry}
              material={materials.WhiteMaterial}
              position={[-1, 0, -0.047]}
            />
            <mesh
              name="Key_W"
              castShadow
              receiveShadow
              geometry={nodes.Key_W.geometry}
              material={materials.WhiteMaterial}
              position={[-0.469, 0, 0.359]}
            />
            <mesh
              name="Key_X"
              castShadow
              receiveShadow
              geometry={nodes.Key_X.geometry}
              material={materials.WhiteMaterial}
              position={[-0.594, 0, -0.047]}
            />
            <mesh
              name="Key_Y"
              castShadow
              receiveShadow
              geometry={nodes.Key_Y.geometry}
              material={materials.WhiteMaterial}
              position={[-1.281, 0, 0.359]}
            />
            <mesh
              name="Key_Z"
              castShadow
              receiveShadow
              geometry={nodes.Key_Z.geometry}
              material={materials.WhiteMaterial}
              position={[-0.391, 0, -0.047]}
            />
          </group>
        </group>
        <group name="Mouse" position={[-1.297, 0, -0.461]} rotation={[0, Math.PI / 8, 0]}>
          <mesh
            name="MouseBody"
            castShadow
            receiveShadow
            geometry={nodes.MouseBody.geometry}
            material={materials.WhiteMaterial}
            position={[0, -0.125, -0.063]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/computer.glb')
