/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF } from '@react-three/drei'

export function DonutModel(props) {
    const { nodes, materials } = useGLTF('/assets/models/donut.gltf')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={nodes.Torus.material}
            >
                <Outlines thickness={10} color="hotpink" />
            </mesh>
        </group>
    )
}

useGLTF.preload('/assets/models/donut.gltf')
