/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF } from '@react-three/drei';

export function DonutModel({ hover }) {
    const { nodes } = useGLTF('/assets/models/donut.gltf')
    return (
        <group dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={nodes.Torus.material}
            >
                {hover && <Outlines thickness={8} color="#1E4BF5" />}
            </mesh>
        </group>
    )
}

useGLTF.preload('/assets/models/donut.gltf')
