/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF } from '@react-three/drei'

export function HCAModel({ hover, ...props }) {
    const { nodes, materials } = useGLTF('/assets/models/hca_mannequin.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                name="Mannequin"
                castShadow
                receiveShadow
                geometry={nodes.Mannequin.geometry}
                material={materials.WhiteMaterial}
            >
                {hover && <Outlines thickness={8} color="#1E4BF5" />}
            </mesh>
        </group>
    )
}

useGLTF.preload('/assets/models/hca_mannequin.glb')
