/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF } from '@react-three/drei'

export function OctreeModel({ hover, ...props }) {
    const { nodes, materials } = useGLTF('/assets/models/octree.glb')
    return (
        <group {...props} dispose={null}>
            <group name="OctreeRoot" position={[0.011, 0.011, 0.102]}>
                <mesh
                    name="Hitbox"
                    geometry={nodes.Hitbox.geometry}
                    material={materials.TransparentMaterial}
                />
                <mesh
                    name="Octree"
                    castShadow
                    receiveShadow
                    geometry={nodes.Octree.geometry}
                    material={nodes.Octree.material}
                    position={[0, 0.482, 0]}
                    scale={0.453}
                >
                    {hover && <Outlines thickness={8} color="#1E4BF5" />}
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/assets/models/octree.glb')
