/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF } from '@react-three/drei'

export function PokeMapsModel({ hover, ...props }) {
    const { nodes, materials } = useGLTF('/assets/models/pokemaps_pin.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                name="Pin"
                castShadow
                receiveShadow
                geometry={nodes.Pin.geometry}
                material={nodes.Pin.material}
                position={[0.011, 0.011, 0.102]}
            >
                {hover && <Outlines thickness={8} color="#1E4BF5" />}
            </mesh>
        </group>
    )
}

useGLTF.preload('/assets/models/pokemaps_pin.glb')
